application.data-dir: /Users/STI/restservice
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/bootcamp
        username: root
        password: root
        initialization-mode: always
        continue-on-error: true
    jpa:
     hibernate:
        ddl-auto: update
     generate-ddl: true
     show-sql: true
     properties:
        hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect
    messages:
     basename: i18n/messages
    servlet:
     multipart:
       enabled: true
       max-file-size: 2MB
       max-request-size: 2MB